# -*- coding: utf-8 -*-

COUNTRY_CHOICES = [
    (u'AF', 'Afghanistan'),
    (u'AX', 'Åland Islands'),
    (u'AL', 'Albania'),
    (u'DZ', 'Algeria'),
    (u'AS', 'American Samoa'),
    (u'AD', 'Andorra'),
    (u'AO', 'Angola'),
    (u'AI', 'Anguilla'),
    (u'AQ', 'Antarctica'),
    (u'AG', 'Antigua and Barbuda'),
    (u'AR', 'Argentina'),
    (u'AM', 'Armenia'),
    (u'AW', 'Aruba'),
    (u'AU', 'Australia'),
    (u'AT', 'Austria'),
    (u'AZ', 'Azerbaijan'),
    (u'BS', 'Bahamas'),
    (u'BH', 'Bahrain'),
    (u'BD', 'Bangladesh'),
    (u'BB', 'Barbados'),
    (u'BY', 'Belarus'),
    (u'BE', 'Belgium'),
    (u'BZ', 'Belize'),
    (u'BJ', 'Benin'),
    (u'BM', 'Bermuda'),
    (u'BT', 'Bhutan'),
    (u'BO', 'Bolivia, Plurinational State of'),
    (u'BQ', 'Bonaire, Sint Eustatius and Saba'),
    (u'BA', 'Bosnia and Herzegovina'),
    (u'BW', 'Botswana'),
    (u'BV', 'Bouvet Island'),
    (u'BR', 'Brazil'),
    (u'IO', 'British Indian Ocean Territory'),
    (u'BN', 'Brunei Darussalam'),
    (u'BG', 'Bulgaria'),
    (u'BF', 'Burkina Faso'),
    (u'BI', 'Burundi'),
    (u'KH', 'Cambodia'),
    (u'CM', 'Cameroon'),
    (u'CA', 'Canada'),
    (u'CV', 'Cape Verde'),
    (u'KY', 'Cayman Islands'),
    (u'CF', 'Central African Republic'),
    (u'TD', 'Chad'),
    (u'CL', 'Chile'),
    (u'CN', 'China'),
    (u'CX', 'Christmas Island'),
    (u'CC', 'Cocos (Keeling) Islands'),
    (u'CO', 'Colombia'),
    (u'KM', 'Comoros'),
    (u'CG', 'Congo'),
    (u'CD', 'Congo, The Democratic Republic of the'),
    (u'CK', 'Cook Islands'),
    (u'CR', 'Costa Rica'),
    (u'CI', "Côte d’Ivoire"),
    (u'HR', 'Croatia'),
    (u'CU', 'Cuba'),
    (u'CW', 'Cura\xe7ao'),
    (u'CY', 'Cyprus'),
    (u'CZ', 'Czech Republic'),
    (u'DK', 'Denmark'),
    (u'DJ', 'Djibouti'),
    (u'DM', 'Dominica'),
    (u'DO', 'Dominican Republic'),
    (u'EC', 'Ecuador'),
    (u'EG', 'Egypt'),
    (u'SV', 'El Salvador'),
    (u'GQ', 'Equatorial Guinea'),
    (u'ER', 'Eritrea'),
    (u'EE', 'Estonia'),
    (u'ET', 'Ethiopia'),
    (u'FK', 'Falkland Islands (Malvinas)'),
    (u'FO', 'Faroe Islands'),
    (u'FJ', 'Fiji'),
    (u'FI', 'Finland'),
    (u'FR', 'France'),
    (u'GF', 'French Guiana'),
    (u'PF', 'French Polynesia'),
    (u'TF', 'French Southern Territories'),
    (u'GA', 'Gabon'),
    (u'GM', 'Gambia'),
    (u'GE', 'Georgia'),
    (u'DE', 'Germany'),
    (u'GH', 'Ghana'),
    (u'GI', 'Gibraltar'),
    (u'GR', 'Greece'),
    (u'GL', 'Greenland'),
    (u'GD', 'Grenada'),
    (u'GP', 'Guadeloupe'),
    (u'GU', 'Guam'),
    (u'GT', 'Guatemala'),
    (u'GG', 'Guernsey'),
    (u'GN', 'Guinea'),
    (u'GW', 'Guinea-Bissau'),
    (u'GY', 'Guyana'),
    (u'HT', 'Haiti'),
    (u'HM', 'Heard Island and McDonald Islands'),
    (u'VA', 'Holy See (Vatican City State)'),
    (u'HN', 'Honduras'),
    (u'HK', 'Hong Kong'),
    (u'HU', 'Hungary'),
    (u'IS', 'Iceland'),
    (u'IN', 'India'),
    (u'ID', 'Indonesia'),
    (u'IR', 'Iran, Islamic Republic of'),
    (u'IQ', 'Iraq'),
    (u'IE', 'Ireland'),
    (u'IM', 'Isle of Man'),
    (u'IL', 'Israel'),
    (u'IT', 'Italy'),
    (u'JM', 'Jamaica'),
    (u'JP', 'Japan'),
    (u'JE', 'Jersey'),
    (u'JO', 'Jordan'),
    (u'KZ', 'Kazakhstan'),
    (u'KE', 'Kenya'),
    (u'KI', 'Kiribati'),
    (u'KP', "Korea, Democratic People's Republic of"),
    (u'KR', 'Korea, Republic of'),
    (u'KW', 'Kuwait'),
    (u'KG', 'Kyrgyzstan'),
    (u'LA', "Lao People's Democratic Republic"),
    (u'LV', 'Latvia'),
    (u'LB', 'Lebanon'),
    (u'LS', 'Lesotho'),
    (u'LR', 'Liberia'),
    (u'LY', 'Libya'),
    (u'LI', 'Liechtenstein'),
    (u'LT', 'Lithuania'),
    (u'LU', 'Luxembourg'),
    (u'MO', 'Macao'),
    (u'MK', 'Macedonia, Republic of'),
    (u'MG', 'Madagascar'),
    (u'MW', 'Malawi'),
    (u'MY', 'Malaysia'),
    (u'MV', 'Maldives'),
    (u'ML', 'Mali'),
    (u'MT', 'Malta'),
    (u'MH', 'Marshall Islands'),
    (u'MQ', 'Martinique'),
    (u'MR', 'Mauritania'),
    (u'MU', 'Mauritius'),
    (u'YT', 'Mayotte'),
    (u'MX', 'Mexico'),
    (u'FM', 'Micronesia, Federated States of'),
    (u'MD', 'Moldova, Republic of'),
    (u'MC', 'Monaco'),
    (u'MN', 'Mongolia'),
    (u'ME', 'Montenegro'),
    (u'MS', 'Montserrat'),
    (u'MA', 'Morocco'),
    (u'MZ', 'Mozambique'),
    (u'MM', 'Myanmar'),
    (u'NA', 'Namibia'),
    (u'NR', 'Nauru'),
    (u'NP', 'Nepal'),
    (u'NL', 'Netherlands'),
    (u'NC', 'New Caledonia'),
    (u'NZ', 'New Zealand'),
    (u'NI', 'Nicaragua'),
    (u'NE', 'Niger'),
    (u'NG', 'Nigeria'),
    (u'NU', 'Niue'),
    (u'NF', 'Norfolk Island'),
    (u'MP', 'Northern Mariana Islands'),
    (u'NO', 'Norway'),
    (u'OM', 'Oman'),
    (u'PK', 'Pakistan'),
    (u'PW', 'Palau'),
    (u'PS', 'Palestine, State of'),
    (u'PA', 'Panama'),
    (u'PG', 'Papua New Guinea'),
    (u'PY', 'Paraguay'),
    (u'PE', 'Peru'),
    (u'PH', 'Philippines'),
    (u'PN', 'Pitcairn'),
    (u'PL', 'Poland'),
    (u'PT', 'Portugal'),
    (u'PR', 'Puerto Rico'),
    (u'QA', 'Qatar'),
    (u'RE', 'R\xe9union'),
    (u'RO', 'Romania'),
    (u'RU', 'Russian Federation'),
    (u'RW', 'Rwanda'),
    (u'BL', 'Saint Barthélemy'),
    (u'SH', 'Saint Helena, Ascension and Tristan da Cunha'),
    (u'KN', 'Saint Kitts and Nevis'),
    (u'LC', 'Saint Lucia'),
    (u'MF', 'Saint Martin (French part)'),
    (u'PM', 'Saint Pierre and Miquelon'),
    (u'VC', 'Saint Vincent and the Grenadines'),
    (u'WS', 'Samoa'),
    (u'SM', 'San Marino'),
    (u'ST', 'Sao Tome and Principe'),
    (u'SA', 'Saudi Arabia'),
    (u'SN', 'Senegal'),
    (u'RS', 'Serbia'),
    (u'SC', 'Seychelles'),
    (u'SL', 'Sierra Leone'),
    (u'SG', 'Singapore'),
    (u'SX', 'Sint Maarten (Dutch part)'),
    (u'SK', 'Slovakia'),
    (u'SI', 'Slovenia'),
    (u'SB', 'Solomon Islands'),
    (u'SO', 'Somalia'),
    (u'ZA', 'South Africa'),
    (u'GS', 'South Georgia and the South Sandwich Islands'),
    (u'ES', 'Spain'),
    (u'LK', 'Sri Lanka'),
    (u'SD', 'Sudan'),
    (u'SR', 'Suriname'),
    (u'SS', 'South Sudan'),
    (u'SJ', 'Svalbard and Jan Mayen'),
    (u'SZ', 'Swaziland'),
    (u'SE', 'Sweden'),
    (u'CH', 'Switzerland'),
    (u'SY', 'Syrian Arab Republic'),
    (u'TW', 'Taiwan'),
    (u'TJ', 'Tajikistan'),
    (u'TZ', 'Tanzania, United Republic of'),
    (u'TH', 'Thailand'),
    (u'TL', 'Timor-Leste'),
    (u'TG', 'Togo'),
    (u'TK', 'Tokelau'),
    (u'TO', 'Tonga'),
    (u'TT', 'Trinidad and Tobago'),
    (u'TN', 'Tunisia'),
    (u'TR', 'Turkey'),
    (u'TM', 'Turkmenistan'),
    (u'TC', 'Turks and Caicos Islands'),
    (u'TV', 'Tuvalu'),
    (u'UG', 'Uganda'),
    (u'UA', 'Ukraine'),
    (u'AE', 'United Arab Emirates'),
    (u'GB', 'United Kingdom'),
    (u'US', 'United States'),
    (u'UM', 'United States Minor Outlying Islands'),
    (u'UY', 'Uruguay'),
    (u'UZ', 'Uzbekistan'),
    (u'VU', 'Vanuatu'),
    (u'VE', 'Venezuela, Bolivarian Republic of'),
    (u'VN', 'Viet Nam'),
    (u'VG', 'Virgin Islands, British'),
    (u'VI', 'Virgin Islands, U.S.'),
    (u'WF', 'Wallis and Futuna'),
    (u'EH', 'Western Sahara'),
    (u'YE', 'Yemen'),
    (u'ZM', 'Zambia'),
    (u'ZW', 'Zimbabwe')]

TOP_COUNTRIES = ('NZ', 'AU')
COUNTRY_CHOICES = [c for c in COUNTRY_CHOICES if c[0] in TOP_COUNTRIES] + \
                  [c for c in COUNTRY_CHOICES if c[0] not in TOP_COUNTRIES]
