# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=191, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='cost')),
                ('min_cart_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_cart_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_options', to='shipping.Option')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_options', to='regions.Region')),
            ],
            options={
                'ordering': ('region__name', 'option'),
            },
        ),
    ]
