# Generated by Django 2.1 on 2018-08-08 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='slug',
        ),
    ]
