# Generated by Django 2.1 on 2018-08-09 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_remove_option_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_options', to='shipping.Option', verbose_name='name'),
        ),
    ]
