# Generated by Django 2.1 on 2018-08-09 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170720_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='suburb',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='Suburb'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shoptools_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
