CURRENCIES = [
    ("NZD", "New Zealand Dollar"),
    ("AUD", "Australia Dollar"),
    ("USD", "United States Dollar"),

    ("AFN", "Afghanistan Afghani"),
    ("ALL", "Albania Lek"),
    ("DZD", "Algeria Dinar"),
    ("AOA", "Angola Kwanza"),
    ("ARS", "Argentina Peso"),
    ("AMD", "Armenia Dram"),
    ("AWG", "Aruba Guilder"),
    ("AZN", "Azerbaijan Manat"),
    ("BSD", "Bahamas Dollar"),
    ("BHD", "Bahrain Dinar"),
    ("BDT", "Bangladesh Taka"),
    ("BBD", "Barbados Dollar"),
    ("BYN", "Belarus Ruble"),
    ("BZD", "Belize Dollar"),
    ("BMD", "Bermuda Dollar"),
    ("BTN", "Bhutan Ngultrum"),
    ("BOB", "Bolivia Bolíviano"),
    ("BAM", "Bosnia and Herzegovina Convertible Marka"),
    ("BWP", "Botswana Pula"),
    ("BRL", "Brazil Real"),
    ("GBP", "British Pound"),
    ("BND", "Brunei Darussalam Dollar"),
    ("BGN", "Bulgaria Lev"),
    ("BIF", "Burundi Franc"),
    ("CAD", "Canada Dollar"),
    ("CVE", "Cape Verde Escudo"),
    ("CLP", "Chile Peso"),
    ("CNY", "China Yuan Renminbi"),
    ("COP", "Colombia Peso"),
    ("CDF", "Congo/Kinshasa Franc"),
    ("CRC", "Costa Rica Colon"),
    ("HRK", "Croatia Kuna"),
    ("CUC", "Cuba Convertible Peso"),
    ("CUP", "Cuba Peso"),
    ("CZK", "Czech Republic Koruna"),
    ("DJF", "Djibouti Franc"),
    ("DKK", "Denmark Krone"),
    ("DOP", "Dominican Republic Peso"),
    ("XCD", "East Caribbean Dollar"),
    ("EGP", "Egypt Pound"),
    ("ERN", "Eritrea Nakfa"),
    ("ETB", "Ethiopia Birr"),
    ("EUR", "Euro Member Countries"),
    ("FJD", "Fiji Dollar"),
    ("FKP", "Falkland Islands (Malvinas) Pound"),
    ("GEL", "Georgia Lari"),
    ("GGP", "Guernsey Pound"),
    ("GHS", "Ghana Cedi"),
    ("GIP", "Gibraltar Pound"),
    ("GMD", "Gambia Dalasi"),
    ("GNF", "Guinea Franc"),
    ("GTQ", "Guatemala Quetzal"),
    ("GYD", "Guyana Dollar"),
    ("HKD", "Hong Kong Dollar"),
    ("HNL", "Honduras Lempira"),
    ("HTG", "Haiti Gourde"),
    ("HUF", "Hungary Forint"),
    ("IDR", "Indonesia Rupiah"),
    ("XDR", "International Monetary Fund (IMF) Special Drawing Rights"),
    ("ILS", "Israel Shekel"),
    ("IMP", "Isle of Man Pound"),
    ("INR", "India Rupee"),
    ("IQD", "Iraq Dinar"),
    ("IRR", "Iran Rial"),
    ("ISK", "Iceland Krona"),
    ("JEP", "Jersey Pound"),
    ("JMD", "Jamaica Dollar"),
    ("JOD", "Jordan Dinar"),
    ("JPY", "Japan Yen"),
    ("KES", "Kenya Shilling"),
    ("KGS", "Kyrgyzstan Som"),
    ("KHR", "Cambodia Riel"),
    ("XAF", "Communauté Financière Africaine (BEAC) CFA Franc BEAC"),
    ("KMF", "Comorian Franc"),
    ("KPW", "Korea (North) Won"),
    ("KRW", "Korea (South) Won"),
    ("KWD", "Kuwait Dinar"),
    ("KYD", "Cayman Islands Dollar"),
    ("KZT", "Kazakhstan Tenge"),
    ("LAK", "Laos Kip"),
    ("LBP", "Lebanon Pound"),
    ("LKR", "Sri Lanka Rupee"),
    ("LRD", "Liberia Dollar"),
    ("LSL", "Lesotho Loti"),
    ("LYD", "Libya Dinar"),
    ("MAD", "Morocco Dirham"),
    ("MDL", "Moldova Leu"),
    ("MGA", "Madagascar Ariary"),
    ("MKD", "Macedonia Denar"),
    ("MMK", "Myanmar (Burma) Kyat"),
    ("MNT", "Mongolia Tughrik"),
    ("MOP", "Macau Pataca"),
    ("MRO", "Mauritania Ouguiya"),
    ("MUR", "Mauritius Rupee"),
    ("MVR", "Maldives (Maldive Islands) Rufiyaa"),
    ("MWK", "Malawi Kwacha"),
    ("MXN", "Mexico Peso"),
    ("MYR", "Malaysia Ringgit"),
    ("MZN", "Mozambique Metical"),
    ("NAD", "Namibia Dollar"),
    ("ANG", "Netherlands Antilles Guilder"),
    ("NGN", "Nigeria Naira"),
    ("NIO", "Nicaragua Cordoba"),
    ("NOK", "Norway Krone"),
    ("NPR", "Nepal Rupee"),
    ("OMR", "Oman Rial"),
    ("PAB", "Panama Balboa"),
    ("PEN", "Peru Sol"),
    ("PGK", "Papua New Guinea Kina"),
    ("PHP", "Philippines Peso"),
    ("PKR", "Pakistan Rupee"),
    ("PLN", "Poland Zloty"),
    ("PYG", "Paraguay Guarani"),
    ("QAR", "Qatar Riyal"),
    ("RON", "Romania Leu"),
    ("RSD", "Serbia Dinar"),
    ("RUB", "Russia Ruble"),
    ("RWF", "Rwanda Franc"),
    ("SAR", "Saudi Arabia Riyal"),
    ("SBD", "Solomon Islands Dollar"),
    ("SCR", "Seychelles Rupee"),
    ("SDG", "Sudan Pound"),
    ("SEK", "Sweden Krona"),
    ("CHF", "Switzerland Franc"),
    ("SGD", "Singapore Dollar"),
    ("SHP", "Saint Helena Pound"),
    ("SLL", "Sierra Leone Leone"),
    ("SOS", "Somalia Shilling"),
    ("SPL*", "Seborga Luigino"),
    ("SRD", "Suriname Dollar"),
    ("STD", "São Tomé and Príncipe Dobra"),
    ("SVC", "El Salvador Colon"),
    ("SYP", "Syria Pound"),
    ("SZL", "Swaziland Lilangeni"),
    ("THB", "Thailand Baht"),
    ("TJS", "Tajikistan Somoni"),
    ("TMT", "Turkmenistan Manat"),
    ("TND", "Tunisia Dinar"),
    ("TOP", "Tonga Pa'anga"),
    ("TRY", "Turkey Lira"),
    ("TTD", "Trinidad and Tobago Dollar"),
    ("TVD", "Tuvalu Dollar"),
    ("TWD", "Taiwan New Dollar"),
    ("TZS", "Tanzania Shilling"),
    ("UAH", "Ukraine Hryvnia"),
    ("UGX", "Uganda Shilling"),
    ("AED", "United Arab Emirates Dirham"),
    ("UYU", "Uruguay Peso"),
    ("UZS", "Uzbekistan Som"),
    ("VEF", "Venezuela Bolívar"),
    ("VND", "Viet Nam Dong"),
    ("VUV", "Vanuatu Vatu"),
    ("WST", "Samoa Tala"),
    ("XOF", "Communauté Financière Africaine (BCEAO) Franc"),
    ("XPF", "Comptoirs Français du Pacifique (CFP) Franc"),
    ("YER", "Yemen Rial"),
    ("ZAR", "South Africa Rand"),
    ("ZMW", "Zambia Kwacha"),
    ("ZWD", "Zimbabwe Dollar"),
]
