# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 01:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import shoptools.cart.base
import shoptools.cart.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1023)),
                ('city', models.CharField(max_length=255, verbose_name='Town / City')),
                ('postcode', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], default='shipping', max_length=20)),
                ('name', models.CharField(default='', max_length=1023)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Order number')),
                ('secret', models.UUIDField(db_index=True, default=shoptools.cart.util.make_uuid, editable=False)),
                ('currency', models.CharField(default='NZD', editable=False, max_length=3)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Payment Failed'), (3, 'Paid'), (4, 'Shipped')], default=1)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('delivery_notes', models.TextField(blank=True, default='')),
                ('gift_message', models.TextField(blank=True, default='')),
                ('receive_email', models.BooleanField(default=False, verbose_name='Receive our email news and offers')),
                ('_shipping_cost', models.DecimalField(db_column='shipping_cost', decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='shipping cost')),
                ('_shipping_options', models.TextField(blank=True, db_column='shipping_options', default='', editable=False, verbose_name='shipping options')),
                ('dispatched', models.DateTimeField(editable=False, null=True)),
                ('success_page_viewed', models.BooleanField(default=False, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, shoptools.cart.base.ICart),
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('quantity', models.IntegerField()),
                ('options', models.TextField(default='')),
                ('_total', models.DecimalField(db_column='total', decimal_places=2, max_digits=8)),
                ('_description', models.CharField(blank=True, db_column='description', max_length=255)),
                ('item_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('parent_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='checkout.Order')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, shoptools.cart.base.ICartLine),
        ),
        migrations.AddField(
            model_name='address',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='checkout.Order'),
        ),
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together=set([('item_content_type', 'item_object_id', 'parent_object', 'options')]),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('order', 'address_type')]),
        ),
    ]
