# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='_shipping_options',
        ),
        migrations.AddField(
            model_name='order',
            name='_shipping_option',
            field=models.CharField(blank=True, db_column='shipping_option', default='', editable=False, max_length=255, verbose_name='shipping option'),
        ),
        migrations.AlterField(
            model_name='giftrecipient',
            name='address',
            field=models.CharField(max_length=1023, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='giftrecipient',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='giftrecipient',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='giftrecipient',
            name='postcode',
            field=models.CharField(max_length=100, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='giftrecipient',
            name='state',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='State'),
        ),
    ]
