# Generated by Django 2.1 on 2018-08-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20180723_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receive_email',
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='', max_length=1023),
        ),
        migrations.AddField(
            model_name='address',
            name='suburb',
            field=models.CharField(blank=True, default='', max_length=1023, verbose_name='Suburb'),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
