# Generated by Django 2.1 on 2018-08-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20180807_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery',
        ),
    ]
