# Generated by Django 2.0.7 on 2018-07-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basevoucher',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedvoucher',
            name='currency_code',
            field=models.CharField(default='NZD', editable=False, max_length=4),
        ),
        migrations.AddField(
            model_name='fixedvoucher',
            name='currency_symbol',
            field=models.CharField(default='$', editable=False, max_length=1),
        ),
    ]
