# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import shoptools.contrib.paypal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('intent', models.CharField(choices=[('sale', 'Sale'), ('authorise', 'Authorise'), ('order', 'Order')], max_length=9)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('paypalrestsdk_id', models.CharField(db_index=True, editable=False, max_length=100)),
                ('secret', models.CharField(db_index=True, default=shoptools.contrib.paypal.models.make_uuid, editable=False, max_length=32, unique=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('-created', '-id'),
            },
        ),
    ]
