# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 12:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0008_auto_20160701_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Leave blank to auto-generate', max_length=32, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('limit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('minimum_spend', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='FixedVoucher',
            fields=[
                ('basevoucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vouchers.BaseVoucher')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_line', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.OrderLine')),
            ],
            bases=('vouchers.basevoucher',),
        ),
        migrations.CreateModel(
            name='FreeShippingVoucher',
            fields=[
                ('basevoucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vouchers.BaseVoucher')),
            ],
            bases=('vouchers.basevoucher',),
        ),
        migrations.CreateModel(
            name='PercentageVoucher',
            fields=[
                ('basevoucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vouchers.BaseVoucher')),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            bases=('vouchers.basevoucher',),
        ),
        migrations.AddField(
            model_name='discount',
            name='base_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.BaseVoucher'),
        ),
        migrations.AddField(
            model_name='discount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Order'),
        ),
    ]
