# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 10:03
from __future__ import unicode_literals

import shoptools.abstractions.models
import shoptools.util
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('secret', models.UUIDField(db_index=True, default=shoptools.util.make_uuid, editable=False)),
                ('_shipping_options', models.TextField(blank=True, db_column='shipping_options', default='', editable=False, verbose_name='shipping options')),
                ('_voucher_codes', models.TextField(blank=True, db_column='voucher_codes', default='', editable=False, verbose_name='voucher codes')),
                ('order_obj_id', models.PositiveIntegerField(null=True)),
                ('currency', models.CharField(default='NZD', editable=False, max_length=3)),
                ('order_obj_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, shoptools.abstractions.models.ICart),
        ),
        migrations.CreateModel(
            name='SavedCartLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('quantity', models.IntegerField()),
                ('item_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('parent_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.SavedCart')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, shoptools.abstractions.models.ICartLine),
        ),
        migrations.AlterUniqueTogether(
            name='savedcartline',
            unique_together=set([('item_content_type', 'item_object_id', 'parent_object')]),
        ),
    ]
