# Generated by Django 2.0.7 on 2018-07-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcart',
            name='_shipping_options',
        ),
        migrations.RemoveField(
            model_name='savedcart',
            name='currency',
        ),
        migrations.AddField(
            model_name='savedcart',
            name='_shipping_option',
            field=models.PositiveSmallIntegerField(blank=True, db_column='shipping_option', editable=False, null=True, verbose_name='shipping option'),
        ),
        migrations.AddField(
            model_name='savedcartline',
            name='_options',
            field=models.TextField(blank=True, db_column='options', default=''),
        ),
        migrations.AlterUniqueTogether(
            name='savedcartline',
            unique_together={('item_content_type', 'item_object_id', 'parent_object', '_options')},
        ),
    ]
