# Generated by Django 2.1 on 2018-08-08 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20180723_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcart',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='savedcartline',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
