# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 10:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shoptools.abstractions.models
import shoptools.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritesLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('quantity', models.IntegerField()),
                ('_options', models.TextField(db_column='options', default='')),
                ('item_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, shoptools.abstractions.models.ICartLine),
        ),
        migrations.CreateModel(
            name='FavouritesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('secret', models.UUIDField(db_index=True, default=shoptools.util.make_uuid, editable=False)),
                ('name', models.CharField(blank=True, default='', max_length=191)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
            bases=(models.Model, shoptools.abstractions.models.ICart),
        ),
        migrations.AddField(
            model_name='favouritesline',
            name='parent_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favourites.FavouritesList'),
        ),
        migrations.AlterUniqueTogether(
            name='favouritesline',
            unique_together=set([('item_content_type', 'item_object_id', 'parent_object', '_options')]),
        ),
    ]
