# Generated by Django 2.1 on 2018-08-09 22:02

from django.db import migrations


def set_name(apps, schema_editor):
    FavouritesList = apps.get_model('favourites', 'FavouritesList')

    for favourites_list in FavouritesList.objects.all():
        if not favourites_list.name:
            favourites_list.name = 'favourites'
            favourites_list.save()


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_name, lambda _: None),
    ]
