# Generated by Django 2.1 on 2018-08-09 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0002_auto_20180809_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritesline',
            name='_options',
            field=models.TextField(blank=True, db_column='options', default=''),
        ),
        migrations.AlterField(
            model_name='favouritesline',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='favouriteslist',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='favouriteslist',
            name='name',
            field=models.CharField(max_length=191),
        ),
    ]
