# Generated by Django 2.1 on 2018-08-13 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shoptools.abstractions.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('favourites', '0003_auto_20180809_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_object_id', models.PositiveIntegerField()),
            ],
            bases=(models.Model, shoptools.abstractions.models.ICartItem),
        ),
        migrations.AlterField(
            model_name='favouriteslist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favouritesitem',
            name='favourites_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_items', to='favourites.FavouritesList'),
        ),
        migrations.AddField(
            model_name='favouritesitem',
            name='item_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
    ]
